services:
  incidentiq.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Cosmos__Endpoint=https://cosmos:8081
      - Cosmos__DatabaseName=IncidentIQ
      - Cosmos__IncidentsContainerName=Incidents
      - Cosmos__RunbooksContainerName=Runbooks
      - Cosmos__ChangeFeedLeasesContainerName=ChangeFeedLeases
      - SSL_CERT_FILE=/cosmos-certs/ca-bundle.crt

    ports:
      - "7155:8080"
      - "7156:8081"

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  incidentiq.worker:
    environment:
      - DOTNET_ENVIRONMENT=Development