namespace IncidentIQ.Application.Common.Abstractions;

/// <summary>
/// Generates a numeric embedding vector for a piece of text.
///
/// The Application layer depends only on this abstraction and does not know
/// whether embeddings are generated by Azure OpenAI or a deterministic local
/// development implementation.
/// </summary>
public interface IEmbeddingGenerator
{
    /// <summary>
    /// Generates a numeric embedding vector for the given text.
    /// </summary>
    /// <param name="text">The text to generate an embedding for.</param>
    /// <param name="cancellationToken">A token to monitor for cancellation requests.</param>
    /// <returns>A task that represents the asynchronous operation. The task result contains the numeric embedding vector.</returns>
    Task<IReadOnlyList<float>> GenerateAsync(
        string text,
        CancellationToken cancellationToken = default);
}