namespace IncidentIQ.Application.Assistant.Generate;

/// <summary>
/// Represents a grounded answer generated by the IncidentIQ Operational Assistant.
/// </summary>
public sealed record OperationalAnswer(
    IReadOnlyList<OperationalAnswerSection> Sections,
    string Model,
    DateTimeOffset AnsweredAtUtc);