using '../main.bicep'

param location = 'uksouth'
param projectName = 'incidentiq'
param environmentName = 'dev'

param serviceBusMaxDeliveryCount = 5

param tags = {
  project: 'IncidentIQ'
  environment: 'dev'
  managedBy: 'Bicep'
}

// -----------------------------------------------------------------------------
// Incident analysis model
// -----------------------------------------------------------------------------

param azureAiLocation = 'uksouth'

param azureAiModelName = 'gpt-5-mini'
param azureAiModelVersion = '2025-08-07'
param azureAiDeploymentName = 'incident-analysis'
param azureAiDeploymentSkuName = 'GlobalStandard'
param azureAiDeploymentCapacity = 10

// -----------------------------------------------------------------------------
// Runbook embedding model
// -----------------------------------------------------------------------------

param azureAiEmbeddingModelName = 'text-embedding-3-small'
param azureAiEmbeddingModelVersion = '1'
param azureAiEmbeddingDeploymentName = 'runbook-embedding'
param azureAiEmbeddingDeploymentSkuName = 'GlobalStandard'
param azureAiEmbeddingDeploymentCapacity = 10

// Must match the vector dimensions generated by the embedding model and the
// Cosmos RunbookChunks vector policy.
param azureAiEmbeddingDimensions = 1536
